title: "Sergio Rus"
description: "Hi, I'm Sergio. I'm a software engineer really excited about the Web Platform and web performance."
url: "https://www.sergiorus.com"
schema_type: "https://schema.org/BlogPosting"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "page"
paginate: 10
paginate_path: "/blog/page:num/"
permalink: "/blog/:title-:year:month:day/"
highlighter: "pygments"
markdown: "kramdown"
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jekyll-paginate
